// Generated by `node ontology-kit/ontology.mjs build` from
// ontology-kit/lenses.json, source.json and base.json. Do not edit.

import type { Endpoint, LensMapping } from './lens.mjs';

export interface PublishedLens {
  readonly '@id': string;
  readonly release: string;
  readonly name: string;
  readonly source: Endpoint;
  readonly target: Endpoint;
  readonly mapping: LensMapping;
}

export declare const clockifyTimeEntryV1: PublishedLens;
export declare const todoistTaskIssueV1: PublishedLens;
export declare const raindropBookmarkV1: PublishedLens;
export declare const solidBookmarkV1: PublishedLens;
export declare const clockifyTimeEntryV2: PublishedLens;
export declare const todoistTaskIssueV2: PublishedLens;
export declare const raindropBookmarkV2: PublishedLens;

export declare const lenses: {
  readonly 'clockify-time-entry-v1': PublishedLens;
  readonly 'todoist-task-issue-v1': PublishedLens;
  readonly 'raindrop-bookmark-v1': PublishedLens;
  readonly 'solid-bookmark-v1': PublishedLens;
  readonly 'clockify-time-entry-v2': PublishedLens;
  readonly 'todoist-task-issue-v2': PublishedLens;
  readonly 'raindrop-bookmark-v2': PublishedLens;
};
