// Generated by `node ontology-kit/ontology.mjs build` from
// ontology-kit/lenses.json, source.json and base.json. Do not edit.

/** clockify-time-entry-v1 */
export const clockifyTimeEntryV1 = /* @__PURE__ */ JSON.parse(
  '{"@id":"https://ontola.github.io/atomic-plugins/ontology/lenses/clockify-time-entry-v1","release":"https://ontola.github.io/atomic-plugins/ontology/lenses/v1","name":"Clockify time entry ↔ Time entry","source":{"record":{"provider":"clockify.me","resource":"timeEntry","openapi":"APIs/clockify.me/1.0.0-readonly"}},"target":{"class":"https://ontola.github.io/atomic-plugins/ontology/classes/time-entry-v1"},"mapping":{"version":2,"fields":[{"source":"/description","target":"https://atomicdata.dev/properties/name"},{"source":"/timeInterval/start","target":"https://ontola.github.io/atomic-plugins/ontology/properties/work-start","convert":"iso-seconds-to-ms"},{"source":"/timeInterval/end","target":"https://ontola.github.io/atomic-plugins/ontology/properties/work-end","convert":"iso-seconds-to-ms"},{"source":"/billable","target":"https://ontola.github.io/atomic-plugins/ontology/properties/work-billable"}]}}',
);

/** todoist-task-issue-v1 */
export const todoistTaskIssueV1 = /* @__PURE__ */ JSON.parse(
  '{"@id":"https://ontola.github.io/atomic-plugins/ontology/lenses/todoist-task-issue-v1","release":"https://ontola.github.io/atomic-plugins/ontology/lenses/v1","name":"Todoist task ↔ Issue","source":{"record":{"provider":"todoist.com","resource":"task","openapi":"APIs/todoist.com/1"}},"target":{"class":"https://ontola.github.io/atomic-plugins/ontology/classes/issue-v1"},"mapping":{"version":2,"fields":[{"source":"/content","target":"https://atomicdata.dev/properties/name"},{"source":"/description","target":"https://atomicdata.dev/task/v1/body"},{"source":"/checked","target":"https://atomicdata.dev/task/v1/status","convert":"map","args":{"pairs":[[false,["https://atomicdata.dev/task/v1/todo"]],[true,["https://atomicdata.dev/task/v1/done"]]]},"readOnly":true},{"source":"/due/date","target":"https://atomicdata.dev/task/v1/due-date","convert":"day-of","readOnly":true}]}}',
);

/** raindrop-bookmark-v1 */
export const raindropBookmarkV1 = /* @__PURE__ */ JSON.parse(
  '{"@id":"https://ontola.github.io/atomic-plugins/ontology/lenses/raindrop-bookmark-v1","release":"https://ontola.github.io/atomic-plugins/ontology/lenses/v1","name":"Raindrop bookmark ↔ Bookmark","source":{"record":{"provider":"raindrop.io","resource":"raindrop"}},"target":{"class":"https://atomicdata.dev/class/Bookmark"},"mapping":{"version":2,"fields":[{"source":"/title","target":"https://atomicdata.dev/properties/name"},{"source":"/link","target":"https://atomicdata.dev/property/url"},{"source":"/excerpt","target":"https://atomicdata.dev/properties/description"}]}}',
);

/** solid-bookmark-v1 */
export const solidBookmarkV1 = /* @__PURE__ */ JSON.parse(
  '{"@id":"https://ontola.github.io/atomic-plugins/ontology/lenses/solid-bookmark-v1","release":"https://ontola.github.io/atomic-plugins/ontology/lenses/v1","name":"Solid bookmark ↔ Bookmark","source":{"rdf":"http://www.w3.org/2002/01/bookmark#Bookmark"},"target":{"class":"https://atomicdata.dev/class/Bookmark"},"mapping":{"version":2,"fields":[{"source":"/http:~1~1purl.org~1dc~1terms~1title/0/@value","target":"https://atomicdata.dev/properties/name"},{"source":"/http:~1~1www.w3.org~12002~101~1bookmark#recalls/0/@id","target":"https://atomicdata.dev/property/url"}]}}',
);

/** clockify-time-entry-v2 */
export const clockifyTimeEntryV2 = /* @__PURE__ */ JSON.parse(
  '{"@id":"https://ontola.github.io/atomic-plugins/ontology/lenses/clockify-time-entry-v2","release":"https://ontola.github.io/atomic-plugins/ontology/lenses/v2","name":"Clockify time entry ↔ Time entry","source":{"record":{"provider":"clockify.me","resource":"timeEntry","openapi":"APIs/clockify.me/1.0.0-readonly"}},"target":{"class":"https://ontola.github.io/atomic-plugins/ontology/classes/time-entry-v1"},"mapping":{"version":3,"fields":[{"source":"/description","target":"https://atomicdata.dev/properties/name"},{"source":"/timeInterval/start","target":"https://ontola.github.io/atomic-plugins/ontology/properties/work-start","convert":"iso-seconds-to-ms"},{"source":"/timeInterval/end","target":"https://ontola.github.io/atomic-plugins/ontology/properties/work-end","convert":"iso-seconds-to-ms"},{"source":"/billable","target":"https://ontola.github.io/atomic-plugins/ontology/properties/work-billable"}],"guards":[{"at":"/type","in":["REGULAR"],"orAbsent":true},{"at":"/timeInterval/start","is":"present"},{"at":"/timeInterval/end","is":"present"}]}}',
);

/** todoist-task-issue-v2 */
export const todoistTaskIssueV2 = /* @__PURE__ */ JSON.parse(
  '{"@id":"https://ontola.github.io/atomic-plugins/ontology/lenses/todoist-task-issue-v2","release":"https://ontola.github.io/atomic-plugins/ontology/lenses/v2","name":"Todoist task ↔ Issue","source":{"record":{"provider":"todoist.com","resource":"task","openapi":"APIs/todoist.com/1"}},"target":{"class":"https://ontola.github.io/atomic-plugins/ontology/classes/issue-v1"},"mapping":{"version":3,"fields":[{"source":"/content","target":"https://atomicdata.dev/properties/name"},{"source":"/description","target":"https://atomicdata.dev/task/v1/body"},{"source":"/checked","target":"https://atomicdata.dev/task/v1/status","convert":"map","args":{"pairs":[[false,["https://atomicdata.dev/task/v1/todo"]],[true,["https://atomicdata.dev/task/v1/done"]]]},"readOnly":true},{"source":"/due/date","target":"https://atomicdata.dev/task/v1/due-date","convert":"day-of","readOnly":true,"absent":"unset"}],"guards":[{"at":"/is_deleted","notIn":[true]},{"at":"/content","is":"present"}]}}',
);

/** raindrop-bookmark-v2 */
export const raindropBookmarkV2 = /* @__PURE__ */ JSON.parse(
  '{"@id":"https://ontola.github.io/atomic-plugins/ontology/lenses/raindrop-bookmark-v2","release":"https://ontola.github.io/atomic-plugins/ontology/lenses/v2","name":"Raindrop bookmark ↔ Bookmark","source":{"record":{"provider":"raindrop.io","resource":"raindrop"}},"target":{"class":"https://atomicdata.dev/class/Bookmark"},"mapping":{"version":3,"fields":[{"source":"/title","target":"https://atomicdata.dev/properties/name"},{"source":"/link","target":"https://atomicdata.dev/property/url"},{"source":"/excerpt","target":"https://atomicdata.dev/properties/description","absent":"default","default":""}],"guards":[{"at":"/_id","is":"present"}]}}',
);

/** Every published lens by name. Bundles all of them. */
export const lenses = /* @__PURE__ */ Object.freeze({
  'clockify-time-entry-v1': clockifyTimeEntryV1,
  'todoist-task-issue-v1': todoistTaskIssueV1,
  'raindrop-bookmark-v1': raindropBookmarkV1,
  'solid-bookmark-v1': solidBookmarkV1,
  'clockify-time-entry-v2': clockifyTimeEntryV2,
  'todoist-task-issue-v2': todoistTaskIssueV2,
  'raindrop-bookmark-v2': raindropBookmarkV2,
});
