// Generated by `node ontology-kit/ontology.mjs build` from
// ontology-kit/source.json and ontology-kit/base.json. Do not edit.

import type { SharedClass } from './resolver.mjs';

export interface PropertyTerm {
  readonly subject: string;
  readonly datatype: string;
  readonly classtype?: string;
}

/** The ontology base URL, from base.json at build time. */
export declare const BASE: string;

export declare const releases: {
  readonly v1: string;
};

export declare const properties: {
  readonly 'atomic-calendar-day': PropertyTerm;
  readonly 'atomic-calendar-end-day': PropertyTerm;
  readonly 'atomic-calendar-all-day': PropertyTerm;
  readonly 'atomic-calendar-start': PropertyTerm;
  readonly 'atomic-calendar-end': PropertyTerm;
  readonly 'atomic-calendar-location': PropertyTerm;
  readonly 'atomic-calendar-notes': PropertyTerm;
  readonly 'atomic-calendar-recurrence': PropertyTerm;
  readonly 'work-start': PropertyTerm;
  readonly 'work-end': PropertyTerm;
  readonly 'work-project': PropertyTerm;
  readonly 'work-person': PropertyTerm;
  readonly 'work-billable': PropertyTerm;
  readonly 'bank-account': PropertyTerm;
  readonly 'bank-currency': PropertyTerm;
  readonly 'bank-amount': PropertyTerm;
  readonly 'bank-value-date': PropertyTerm;
  readonly 'bank-booking-date': PropertyTerm;
  readonly 'bank-description': PropertyTerm;
  readonly 'bank-reference': PropertyTerm;
  readonly 'money-category': PropertyTerm;
  readonly 'money-note': PropertyTerm;
};

export declare const classes: {
  readonly 'event-v1': SharedClass;
  readonly 'issue-v1': SharedClass;
  readonly 'time-entry-v1': SharedClass;
  readonly 'work-project-v1': SharedClass;
  readonly 'work-person-v1': SharedClass;
  readonly 'bank-transaction-v1': SharedClass;
};
