// Generated by `node ontology-kit/ontology.mjs build` from
// ontology-kit/source.json and ontology-kit/base.json. Do not edit.

export const BASE = 'https://ontola.github.io/atomic-plugins/ontology';

export const releases = Object.freeze({
  v1: 'https://ontola.github.io/atomic-plugins/ontology/v1',
});

export const properties = Object.freeze({
  'atomic-calendar-day': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/atomic-calendar-day',
    datatype: 'https://atomicdata.dev/datatypes/date',
  }),
  'atomic-calendar-end-day': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/atomic-calendar-end-day',
    datatype: 'https://atomicdata.dev/datatypes/date',
  }),
  'atomic-calendar-all-day': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/atomic-calendar-all-day',
    datatype: 'https://atomicdata.dev/datatypes/boolean',
  }),
  'atomic-calendar-start': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/atomic-calendar-start',
    datatype: 'https://atomicdata.dev/datatypes/string',
  }),
  'atomic-calendar-end': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/atomic-calendar-end',
    datatype: 'https://atomicdata.dev/datatypes/string',
  }),
  'atomic-calendar-location': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/atomic-calendar-location',
    datatype: 'https://atomicdata.dev/datatypes/string',
  }),
  'atomic-calendar-notes': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/atomic-calendar-notes',
    datatype: 'https://atomicdata.dev/datatypes/string',
  }),
  'atomic-calendar-recurrence': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/atomic-calendar-recurrence',
    datatype: 'https://atomicdata.dev/datatypes/json',
  }),
  'work-start': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/work-start',
    datatype: 'https://atomicdata.dev/datatypes/timestamp',
  }),
  'work-end': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/work-end',
    datatype: 'https://atomicdata.dev/datatypes/timestamp',
  }),
  'work-project': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/work-project',
    datatype: 'https://atomicdata.dev/datatypes/atomicURL',
    classtype:
      'https://ontola.github.io/atomic-plugins/ontology/classes/work-project-v1',
  }),
  'work-person': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/work-person',
    datatype: 'https://atomicdata.dev/datatypes/atomicURL',
    classtype:
      'https://ontola.github.io/atomic-plugins/ontology/classes/work-person-v1',
  }),
  'work-billable': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/work-billable',
    datatype: 'https://atomicdata.dev/datatypes/boolean',
  }),
  'bank-account': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/bank-account',
    datatype: 'https://atomicdata.dev/datatypes/string',
  }),
  'bank-currency': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/bank-currency',
    datatype: 'https://atomicdata.dev/datatypes/string',
  }),
  'bank-amount': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/bank-amount',
    datatype: 'https://atomicdata.dev/datatypes/string',
  }),
  'bank-value-date': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/bank-value-date',
    datatype: 'https://atomicdata.dev/datatypes/date',
  }),
  'bank-booking-date': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/bank-booking-date',
    datatype: 'https://atomicdata.dev/datatypes/date',
  }),
  'bank-description': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/bank-description',
    datatype: 'https://atomicdata.dev/datatypes/string',
  }),
  'bank-reference': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/bank-reference',
    datatype: 'https://atomicdata.dev/datatypes/string',
  }),
  'money-category': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/money-category',
    datatype: 'https://atomicdata.dev/datatypes/string',
  }),
  'money-note': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/properties/money-note',
    datatype: 'https://atomicdata.dev/datatypes/string',
  }),
});

export const classes = Object.freeze({
  'event-v1': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/classes/event-v1',
    requires: Object.freeze([
      'https://atomicdata.dev/properties/name',
      'https://ontola.github.io/atomic-plugins/ontology/properties/atomic-calendar-day',
    ]),
    recommends: Object.freeze([
      'https://ontola.github.io/atomic-plugins/ontology/properties/atomic-calendar-end-day',
      'https://ontola.github.io/atomic-plugins/ontology/properties/atomic-calendar-all-day',
      'https://ontola.github.io/atomic-plugins/ontology/properties/atomic-calendar-start',
      'https://ontola.github.io/atomic-plugins/ontology/properties/atomic-calendar-end',
      'https://ontola.github.io/atomic-plugins/ontology/properties/atomic-calendar-location',
      'https://ontola.github.io/atomic-plugins/ontology/properties/atomic-calendar-notes',
      'https://ontola.github.io/atomic-plugins/ontology/properties/atomic-calendar-recurrence',
    ]),
  }),
  'issue-v1': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/classes/issue-v1',
    requires: Object.freeze(['https://atomicdata.dev/properties/name']),
    recommends: Object.freeze([
      'https://atomicdata.dev/task/v1/status',
      'https://atomicdata.dev/task/v1/body',
      'https://atomicdata.dev/task/v1/assignee',
      'https://atomicdata.dev/task/v1/due-date',
    ]),
  }),
  'time-entry-v1': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/classes/time-entry-v1',
    requires: Object.freeze([
      'https://ontola.github.io/atomic-plugins/ontology/properties/work-start',
    ]),
    recommends: Object.freeze([
      'https://atomicdata.dev/properties/name',
      'https://ontola.github.io/atomic-plugins/ontology/properties/work-end',
      'https://ontola.github.io/atomic-plugins/ontology/properties/work-project',
      'https://ontola.github.io/atomic-plugins/ontology/properties/work-person',
      'https://ontola.github.io/atomic-plugins/ontology/properties/work-billable',
    ]),
  }),
  'work-project-v1': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/classes/work-project-v1',
    requires: Object.freeze(['https://atomicdata.dev/properties/name']),
    recommends: Object.freeze([]),
  }),
  'work-person-v1': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/classes/work-person-v1',
    requires: Object.freeze(['https://atomicdata.dev/properties/name']),
    recommends: Object.freeze([]),
  }),
  'bank-transaction-v1': Object.freeze({
    subject:
      'https://ontola.github.io/atomic-plugins/ontology/classes/bank-transaction-v1',
    requires: Object.freeze([
      'https://ontola.github.io/atomic-plugins/ontology/properties/bank-account',
      'https://ontola.github.io/atomic-plugins/ontology/properties/bank-currency',
      'https://ontola.github.io/atomic-plugins/ontology/properties/bank-amount',
      'https://ontola.github.io/atomic-plugins/ontology/properties/bank-value-date',
    ]),
    recommends: Object.freeze([
      'https://atomicdata.dev/properties/name',
      'https://ontola.github.io/atomic-plugins/ontology/properties/bank-booking-date',
      'https://ontola.github.io/atomic-plugins/ontology/properties/bank-description',
      'https://ontola.github.io/atomic-plugins/ontology/properties/bank-reference',
      'https://ontola.github.io/atomic-plugins/ontology/properties/money-category',
      'https://ontola.github.io/atomic-plugins/ontology/properties/money-note',
    ]),
  }),
});
