import { readFile, writeFile } from 'node:fs/promises';
const manifest = JSON.parse(
  await readFile(new URL('./manifest.json', import.meta.url), 'utf8'),
);
const source = await readFile(new URL('./plugin.mjs', import.meta.url), 'utf8');
await writeFile(
  new URL('./plugin.js', import.meta.url),
  '// Generated by build.mjs; edit plugin.mjs and manifest.json.\nexport const manifest = ' +
    JSON.stringify(manifest) +
    ';\n' +
    source,
);
