import { readFileSync, writeFileSync } from 'node:fs';
import { stripTypeScriptTypes } from 'node:module';
const read = path => readFileSync(new URL(path, import.meta.url), 'utf8');
// One source of cryptographic truth; no edits or vendored copy of the drop importer.
const crypto = stripTypeScriptTypes(read('../willow-drop/william3.ts'));
const withoutImports = path =>
  read(path).replace(/^import[\s\S]*?;\n/gm, '');
const bundle =
  '// Generated by build.mjs. Sources: codec.mjs, drop.mjs, plugin.mjs, ../willow-drop/william3.ts\n' +
  crypto +
  '\n' +
  read('./codec.mjs') +
  '\n' +
  withoutImports('./drop.mjs') +
  '\n' +
  withoutImports('./plugin.mjs');
const { manifest } = await import(
  'data:text/javascript;base64,' + Buffer.from(bundle).toString('base64')
);

for (const [name, content] of Object.entries({
  'plugin.js': bundle,
  'plugin.json':
    JSON.stringify(manifest, null, 2).replace(
      /\[\n\s*((?:"[^"]*"(?:,\n\s*)?)+)\n\s*\]/g,
      (match, values, offset, text) => {
        const inline = '[' + values.replace(/,\n\s*/g, ', ') + ']';
        const column = offset - text.lastIndexOf('\n', offset) - 1;

        return column + inline.length <= 80 ? inline : match;
      },
    ) + '\n',
})) {
  const target = new URL(name, import.meta.url);
  if (process.argv.includes('--check')) {
    if (readFileSync(target, 'utf8') !== content)
      throw Error(name + ' is stale');
  } else writeFileSync(target, content);
}
