// Generated by build.mjs. Sources: codec.mjs, drop.mjs, plugin.mjs, ../willow-drop/william3.ts
// @wc-ignore-file
/**
 * WILLIAM3, the Bab hash instantiation Willow'25 uses for payload digests
 * (https://bab-hash.org/spec, section 2.3.2). It is BLAKE3 with three changes:
 * different IV constants, a chunk counter that is always 0, and parent nodes
 * whose counter is the byte length of the subtree they cover. Chunks are 1024
 * bytes and digests 32 bytes, as in BLAKE3.
 *
 * Only the unkeyed, whole-payload digest is implemented: enough to check a
 * payload a drop carries in full. Verifiable slice streams (Bab section 3) are
 * not, so drops with partial payload slices are refused in drop.ts.
 *
 * Ported from bab_rs 0.8.1 (`william3/basics.rs`, `william3/portable.rs`,
 * `william3.rs`); the tree shape follows `generic/hasher.rs`.
 */

export const CHUNK_SIZE = 1024;
const BLOCK_LEN = 64;

const IV = new Uint32Array([
  0xc88f633b, 0x4168fbf2, 0x6ba32583, 0xb0ff1847, 0xac57e47d, 0xa8931330,
  0x796a4645, 0x6b28a3ee,
]);

const MSG_SCHEDULE = [
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
  [2, 6, 3, 10, 7, 0, 4, 13, 1, 11, 12, 5, 9, 14, 15, 8],
  [3, 4, 10, 12, 13, 2, 7, 14, 6, 5, 9, 0, 11, 15, 8, 1],
  [10, 7, 12, 9, 14, 3, 13, 15, 4, 0, 11, 2, 5, 8, 1, 6],
  [12, 13, 9, 11, 15, 10, 14, 8, 7, 2, 5, 3, 0, 1, 6, 4],
  [9, 14, 11, 5, 8, 12, 15, 1, 13, 3, 0, 10, 2, 6, 4, 7],
  [11, 15, 5, 0, 1, 9, 8, 6, 14, 10, 2, 12, 3, 4, 7, 13],
];

const CHUNK_START = 1;
const CHUNK_END = 2;
const PARENT = 4;
const ROOT = 8;

const rotr = (x        , n        ) => ((x >>> n) | (x << (32 - n))) >>> 0;

function g(
  s             ,
  a        ,
  b        ,
  c        ,
  d        ,
  x        ,
  y        ,
) {
  s[a] = (s[a] + s[b] + x) >>> 0;
  s[d] = rotr(s[d] ^ s[a], 16);
  s[c] = (s[c] + s[d]) >>> 0;
  s[b] = rotr(s[b] ^ s[c], 12);
  s[a] = (s[a] + s[b] + y) >>> 0;
  s[d] = rotr(s[d] ^ s[a], 8);
  s[c] = (s[c] + s[d]) >>> 0;
  s[b] = rotr(s[b] ^ s[c], 7);
}

/** The BLAKE3 compression function, writing the new chaining value into `cv`. */
function compress(
  cv             ,
  block            ,
  blockLen        ,
  counter        ,
  flags        ,
) {
  const m = new Uint32Array(16);

  for (let i = 0; i < 16; i++)
    m[i] =
      (block[i * 4] |
        (block[i * 4 + 1] << 8) |
        (block[i * 4 + 2] << 16) |
        (block[i * 4 + 3] << 24)) >>>
      0;

  const s = new Uint32Array([
    ...cv,
    IV[0],
    IV[1],
    IV[2],
    IV[3],
    Number(counter & 0xffffffffn),
    Number((counter >> 32n) & 0xffffffffn),
    blockLen,
    flags,
  ]);

  for (const schedule of MSG_SCHEDULE) {
    g(s, 0, 4, 8, 12, m[schedule[0]], m[schedule[1]]);
    g(s, 1, 5, 9, 13, m[schedule[2]], m[schedule[3]]);
    g(s, 2, 6, 10, 14, m[schedule[4]], m[schedule[5]]);
    g(s, 3, 7, 11, 15, m[schedule[6]], m[schedule[7]]);
    g(s, 0, 5, 10, 15, m[schedule[8]], m[schedule[9]]);
    g(s, 1, 6, 11, 12, m[schedule[10]], m[schedule[11]]);
    g(s, 2, 7, 8, 13, m[schedule[12]], m[schedule[13]]);
    g(s, 3, 4, 9, 14, m[schedule[14]], m[schedule[15]]);
  }

  for (let i = 0; i < 8; i++) cv[i] = (s[i] ^ s[i + 8]) >>> 0;
}

/** bab_rs `hash1`: absorb `input` block by block into one chaining value. */
function hash1(
  input            ,
  counter        ,
  flags        ,
  flagsStart        ,
  flagsEnd        ,
)             {
  const cv = new Uint32Array(IV);
  let blockFlags = flags | flagsStart;

  if (input.length === 0) {
    compress(cv, new Uint8Array(BLOCK_LEN), 0, counter, blockFlags | flagsEnd);
  } else {
    for (let offset = 0; offset < input.length; offset += BLOCK_LEN) {
      const rest = input.length - offset;
      const block = new Uint8Array(BLOCK_LEN);
      block.set(input.subarray(offset, offset + Math.min(rest, BLOCK_LEN)));
      if (rest <= BLOCK_LEN) blockFlags |= flagsEnd;
      compress(cv, block, Math.min(rest, BLOCK_LEN), counter, blockFlags);
      blockFlags = flags;
    }
  }

  const out = new Uint8Array(32);

  for (let i = 0; i < 8; i++) {
    out[i * 4] = cv[i] & 0xff;
    out[i * 4 + 1] = (cv[i] >>> 8) & 0xff;
    out[i * 4 + 2] = (cv[i] >>> 16) & 0xff;
    out[i * 4 + 3] = (cv[i] >>> 24) & 0xff;
  }

  return out;
}

const hashChunk = (chunk            , isRoot         ) =>
  hash1(chunk, 0n, 0, CHUNK_START, CHUNK_END | (isRoot ? ROOT : 0));

function hashInner(
  left            ,
  right            ,
  length        ,
  isRoot         ,
) {
  const block = new Uint8Array(BLOCK_LEN);
  block.set(left, 0);
  block.set(right, 32);

  return hash1(block, BigInt(length), PARENT | (isRoot ? ROOT : 0), 0, 0);
}

/** Label of the subtree over `bytes`, which holds `chunks` chunks. */
function label(bytes            , chunks        , isRoot         )             {
  if (chunks <= 1) return hashChunk(bytes, isRoot);
  // Left subtrees are complete: the largest power of two below `chunks`.
  let left = 1;
  while (left * 2 < chunks) left *= 2;
  const split = left * CHUNK_SIZE;

  return hashInner(
    label(bytes.subarray(0, split), left, false),
    label(bytes.subarray(split), chunks - left, false),
    bytes.length,
    isRoot,
  );
}

/** The WILLIAM3 digest of `bytes`: 32 bytes. */
export function william3(bytes            )             {
  return label(bytes, Math.max(1, Math.ceil(bytes.length / CHUNK_SIZE)), true);
}

/** Willow'25 encoding primitives. No authentication or transport is performed.
 * Spec: https://willowprotocol.org/specs/encodings/index.html
 * Parameters: https://willowprotocol.org/specs/willow25/
 */
export const U64_MAX = (1n << 64n) - 1n;
export const PATH_LIMIT = 4096;
export function u64(value) {
  if (typeof value !== 'bigint' || value < 0n || value > U64_MAX)
    throw Error('Expected unsigned 64-bit bigint');

  return value;
}
export function bytes(value, length) {
  if (
    !(value instanceof Uint8Array) ||
    (length !== undefined && value.length !== length)
  )
    throw Error('Invalid byte sequence length');

  return value;
}
export function hex(value) {
  return Array.from(bytes(value), b => b.toString(16).padStart(2, '0')).join(
    '',
  );
}
export function unhex(value) {
  if (typeof value !== 'string' || !/^(?:[0-9a-fA-F]{2})*$/.test(value))
    throw Error('Invalid hexadecimal bytes');

  return Uint8Array.from(value.match(/../g) || [], pair => parseInt(pair, 16));
}
export function utf8(text) {
  if (typeof text !== 'string') throw Error('Expected text');
  const encoded = encodeURIComponent(text),
    out = [];

  for (let i = 0; i < encoded.length; i++) {
    if (encoded[i] === '%') {
      out.push(parseInt(encoded.slice(i + 1, i + 3), 16));
      i += 2;
    } else out.push(encoded.charCodeAt(i));
  }

  return Uint8Array.from(out);
}

const concat = (...parts) =>
  Uint8Array.from(parts.flatMap(part => Array.from(part)));

export function tag(value, width) {
  u64(value);
  if (!Number.isInteger(width) || width < 2 || width > 8)
    throw Error('Invalid compact integer tag width');
  const first = (1 << width) - 4;
  if (value < BigInt(first)) return Number(value);

  return (
    first +
    (value < 256n ? 0 : value < 65536n ? 1 : value < 4294967296n ? 2 : 3)
  );
}

function trailing(value, width) {
  const extra = tag(value, width) - ((1 << width) - 4);
  if (extra < 0) return [];
  const size = [1, 2, 4, 8][extra],
    out = [];
  for (let i = size - 1; i >= 0; i--)
    out.push(Number((value >> BigInt(i * 8)) & 255n));

  return out;
}

export const compact = value =>
  Uint8Array.from([tag(value, 8), ...trailing(value, 8)]);
class Reader {
  constructor(input) {
    this.input = bytes(input);
    this.at = 0;
  }
  take(n) {
    if (!Number.isSafeInteger(n) || n < 0 || n > this.input.length - this.at)
      throw Error('Truncated encoding');
    const result = this.input.slice(this.at, this.at + n);
    this.at += n;

    return result;
  }
  byte() {
    return this.take(1)[0];
  }
  compact(t = this.byte(), width = 8) {
    const extra = t - ((1 << width) - 4);
    if (extra < 0) return BigInt(t);
    let value = 0n;
    for (const b of this.take([1, 2, 4, 8][extra]))
      value = (value << 8n) | BigInt(b);

    return value;
  }
  end() {
    if (this.at !== this.input.length) throw Error('Trailing encoding bytes');
  }
}

export function validatePath(path) {
  if (!Array.isArray(path) || path.length > PATH_LIMIT)
    throw Error('Too many path components');
  let length = 0;

  for (const part of path) {
    if (bytes(part).length > PATH_LIMIT) throw Error('Path component too long');
    length += part.length;
  }

  if (length > PATH_LIMIT) throw Error('Path too long');

  return path;
}
export function encodePath(path) {
  validatePath(path);
  const length = BigInt(path.reduce((n, p) => n + p.length, 0)),
    count = BigInt(path.length);
  const out = [
    (tag(length, 4) << 4) | tag(count, 4),
    ...trailing(length, 4),
    ...trailing(count, 4),
  ];
  path.forEach((part, i) => {
    if (i < path.length - 1) out.push(...compact(BigInt(part.length)));
    out.push(...part);
  });

  return Uint8Array.from(out);
}

function readPath(reader) {
  const header = reader.byte(),
    total = reader.compact(header >>> 4, 4),
    count = reader.compact(header & 15, 4);
  if (total > 4096n || count > 4096n) throw Error('Path limits exceeded');
  if (count === 0n && total !== 0n) throw Error('Empty path claims bytes');
  const path = [];
  let remaining = Number(total);

  for (let i = 0; i < Number(count); i++) {
    const length =
      i === Number(count) - 1 ? BigInt(remaining) : reader.compact();
    if (length > BigInt(remaining))
      throw Error('Component exceeds remaining path bytes');
    path.push(reader.take(Number(length)));
    remaining -= Number(length);
  }

  return path;
}

export function decodePath(input) {
  const reader = new Reader(input),
    path = readPath(reader);
  reader.end();

  return path;
}

const sameBytes = (a, b) =>
  a.length === b.length && a.every((v, i) => v === b[i]);

function pathPrefix(a, b) {
  let i = 0;
  while (i < a.length && i < b.length && sameBytes(a[i], b[i])) i++;

  return i;
}

function relativePath(path, previous) {
  validatePath(previous);
  const prefix = pathPrefix(path, previous);

  return concat(compact(BigInt(prefix)), encodePath(path.slice(prefix)));
}

function readRelativePath(reader, previous) {
  const prefix = reader.compact();
  if (prefix > BigInt(previous.length))
    throw Error('Relative path prefix exceeds reference');

  return validatePath([
    ...previous.slice(0, Number(prefix)).map(p => p.slice()),
    ...readPath(reader),
  ]);
}

export function validateEntry(entry) {
  if (!entry || typeof entry !== 'object') throw Error('Invalid Entry');
  bytes(entry.namespace, 32);
  bytes(entry.subspace, 32);
  bytes(entry.payloadDigest, 32);
  validatePath(entry.path);
  u64(entry.timestamp);
  u64(entry.payloadLength);

  return entry;
}
/** Canonical encode_entry: exact bytes covered by a future Meadowcap signature. */
export function encodeEntry(entry) {
  validateEntry(entry);

  return concat(
    entry.namespace,
    entry.subspace,
    encodePath(entry.path),
    compact(entry.timestamp),
    compact(entry.payloadLength),
    entry.payloadDigest,
  );
}
/** Decode the general EncodeEntry relation (nonminimal tags are allowed).
 * canonical=true additionally requires the unique signing representation.
 */
export function decodeEntry(input, { canonical = false } = {}) {
  const reader = new Reader(input),
    entry = {
      namespace: reader.take(32),
      subspace: reader.take(32),
      path: readPath(reader),
      timestamp: reader.compact(),
      payloadLength: reader.compact(),
      payloadDigest: reader.take(32),
    };
  reader.end();
  validateEntry(entry);
  if (canonical && !sameBytes(input, encodeEntry(entry)))
    throw Error('Noncanonical Entry encoding');

  return entry;
}
/** One minimal EncodeEntryRelativeEntry code, used by Willow sync encodings. */
export function encodeRelativeEntry(entry, previous) {
  validateEntry(entry);
  validateEntry(previous);
  const differentNamespace = !sameBytes(entry.namespace, previous.namespace),
    differentSubspace = !sameBytes(entry.subspace, previous.subspace);
  const forward = entry.timestamp > previous.timestamp,
    delta = forward
      ? entry.timestamp - previous.timestamp
      : previous.timestamp - entry.timestamp;
  const header =
    (differentNamespace ? 128 : 0) |
    (differentSubspace ? 64 : 0) |
    (forward ? 32 : 0) |
    (tag(delta, 2) << 3) |
    tag(entry.payloadLength, 3);

  return concat(
    [header],
    differentNamespace ? entry.namespace : [],
    differentSubspace ? entry.subspace : [],
    trailing(delta, 2),
    trailing(entry.payloadLength, 3),
    relativePath(entry.path, previous.path),
    entry.payloadDigest,
  );
}
export function decodeRelativeEntry(input, previous) {
  validateEntry(previous);
  const reader = new Reader(input),
    header = reader.byte();
  const namespace = header & 128 ? reader.take(32) : previous.namespace.slice(),
    subspace = header & 64 ? reader.take(32) : previous.subspace.slice();
  const delta = reader.compact((header >>> 3) & 3, 2),
    payloadLength = reader.compact(header & 7, 3);
  const timestamp =
    header & 32 ? previous.timestamp + delta : previous.timestamp - delta;
  const entry = {
    namespace,
    subspace,
    timestamp,
    payloadLength,
    path: readRelativePath(reader, previous.path),
    payloadDigest: reader.take(32),
  };
  reader.end();

  return validateEntry(entry);
}

/** Willow Drop Format encoder (https://willowprotocol.org/specs/drop-format/,
 * status "Proposal") for Willow'25 entries with communal capabilities and no
 * delegations, each followed by its whole payload. The byte layout mirrors
 * the decoder in ../willow-drop/drop.ts, which was checked against drops
 * written by willow25 0.7.9; fixtures/verify-drop checks our output with
 * willow25's own DropDecoder. Also: the data model's recommended timestamp
 * and standard base64, both without Node APIs, for the QuickJS sandbox.
 */

/** The Willow'25 example id: the namespace and subspace of the default entry. */
export const DEFAULT_ID =
  '934e6021339e1f013ba94900edc25d8d74c0b4e573768910ae0f507d8c817318';

/** The entry the first entry of a drop is encoded against. */
export function defaultEntry() {
  return {
    namespace: unhex(DEFAULT_ID),
    subspace: unhex(DEFAULT_ID),
    path: [],
    timestamp: 0n,
    payloadLength: 0n,
    payloadDigest: william3(new Uint8Array()),
  };
}

const same = (a, b) => a.length === b.length && a.every((v, i) => v === b[i]);

/** A compact U64 in a 2-bit tag with no inline values: tag 0 means 1 byte,
 * 1 means 2, 2 means 4 and 3 means 8. */
function tag2(value) {
  u64(value);
  const size =
    value < 256n ? 1 : value < 65536n ? 2 : value < 4294967296n ? 4 : 8;
  const out = [];
  for (let i = size - 1; i >= 0; i--)
    out.push(Number((value >> BigInt(i * 8)) & 255n));

  return { tag: [1, 2, 4, 8].indexOf(size), bytes: out };
}

function commonPrefix(a, b) {
  let i = 0;
  while (i < a.length && i < b.length && same(a[i], b[i])) i++;

  return i;
}

/**
 * The drop of `items`, in order. Each item is `{ entry, signature, payload }`:
 * an Entry (as codec.mjs), the 64-byte Ed25519 signature of its subspace key
 * over `encode_entry`, and the whole payload, whose length and WILLIAM3
 * digest must match the entry. Only communal capabilities (the signer is the
 * subspace) are encoded; the namespace must be communal (last byte even).
 */
export function encodeDrop(items) {
  const out = [];
  let previous = defaultEntry();

  for (const { entry, signature, payload } of items) {
    validateEntry(entry);
    if (entry.namespace[31] % 2 !== 0)
      throw Error('Only communal namespaces are encoded');
    if (!(signature instanceof Uint8Array) || signature.length !== 64)
      throw Error('An authorisation signature is 64 bytes');
    if (
      !(payload instanceof Uint8Array) ||
      BigInt(payload.length) !== entry.payloadLength ||
      hex(william3(payload)) !== hex(entry.payloadDigest)
    )
      throw Error('The payload does not match its entry');
    const namespace = !same(entry.namespace, previous.namespace);
    const subspace = !same(entry.subspace, previous.subspace);
    const time = tag2(entry.timestamp);
    const prefix = commonPrefix(entry.path, previous.path);
    // 01: an entry header; 0x20/0x10: namespace/subspace included; the
    // timestamp's tag; 01: the whole payload follows.
    out.push(
      0x40 |
        (namespace ? 0x20 : 0) |
        (subspace ? 0x10 : 0) |
        (time.tag << 2) |
        0x01,
    );
    if (namespace) out.push(...entry.namespace);
    if (subspace) out.push(...entry.subspace);
    out.push(
      ...compact(BigInt(prefix)),
      ...encodePath(entry.path.slice(prefix)),
    );
    out.push(
      ...time.bytes,
      ...compact(entry.payloadLength),
      ...entry.payloadDigest,
    );
    // A communal capability without delegations: an all-zero header.
    out.push(0x00, ...signature, ...payload);
    previous = entry;
  }

  out.push(0x00);

  return Uint8Array.from(out);
}

/** J2000 (2000-01-01 12:00:00 TT = 11:59:27.816 TAI) on a TAI clock, in
 * microseconds since 1970-01-01 00:00 on that clock. As
 * ../willow-drop/mapping.ts and atomic-server's `plugins/willow.rs`. */
const J2000_TAI_US = 946_727_967_816_000n;
/** TAI − UTC from each UTC instant on, in seconds (IERS Bulletin C). */
const LEAP_SECONDS = [
  [1_483_228_800_000_000n, 37n], // 2017-01-01
  [1_435_708_800_000_000n, 36n], // 2015-07-01
  [1_341_100_800_000_000n, 35n], // 2012-07-01
  [1_230_768_000_000_000n, 34n], // 2009-01-01
  [1_136_073_600_000_000n, 33n], // 2006-01-01
  [0n, 32n], // from 1999-01-01, which covers J2000
];

/**
 * A Unix time in milliseconds (an Atomic commit's `createdAt`) as the data
 * model's recommended timestamp: microseconds of TAI since J2000. willow25
 * 0.7.9 reads timestamps through hifitime's J2000_REF_EPOCH (2000-01-02 12:00
 * TAI), 86,432.184 s away from this reading (worm-blossom/willow_rs#62).
 */
export function willowTime(unixMillis) {
  if (typeof unixMillis !== 'bigint')
    throw Error('Expected bigint milliseconds');
  const us = unixMillis * 1000n;
  const [, offset] = LEAP_SECONDS.find(([start]) => us >= start);
  const value = us + offset * 1_000_000n - J2000_TAI_US;
  if (value < 0n) throw Error('Willow timestamps start at J2000');

  return u64(value);
}

const BASE64 =
  'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

/** Standard base64 with padding. */
export function base64(bytes) {
  let out = '';

  for (let i = 0; i < bytes.length; i += 3) {
    const n =
      (bytes[i] << 16) | ((bytes[i + 1] ?? 0) << 8) | (bytes[i + 2] ?? 0);
    out += BASE64[n >> 18] + BASE64[(n >> 12) & 63];
    out += i + 1 < bytes.length ? BASE64[(n >> 6) & 63] : '=';
    out += i + 2 < bytes.length ? BASE64[n & 63] : '=';
  }

  return out;
}


export const P = Object.freeze({
  parent: 'https://atomicdata.dev/properties/parent',
  name: 'https://atomicdata.dev/properties/name',
  description: 'https://atomicdata.dev/properties/description',
  localId: 'https://atomicdata.dev/properties/localId',
  baseline: 'https://atomicdata.dev/properties/importBaseline',
  lastCommit: 'https://atomicdata.dev/properties/lastCommit',
});
/** The host-held Ed25519 key whose public half is this installation's subspace. */
export const WILLOW_KEY = 'willow';
const MAX_SUBJECTS = 32,
  MAX_PAYLOAD_BYTES = 65536;

export const manifest = {
  schemaVersion: 3,
  name: 'willow',
  namespace: 'atomic-plugins',
  version: '0.3.0',
  description:
    'Publish explicitly selected public Atomic properties as a Willow drop of host-signed, Meadowcap-authorised entries.',
  operations: [],
  secrets: [],
  http: {
    mount: 'drive-prefix',
    routes: [
      {
        id: 'drop',
        path: '/willow.drop',
        methods: ['GET'],
        principal: 'anonymous',
        auth: 'none',
      },
    ],
    keys: [
      {
        name: WILLOW_KEY,
        alg: 'ed25519',
        willow: {
          namespace: 'config:namespace',
          pathPrefix: 'config:pathPrefix',
        },
        reason:
          "This installation's Willow subspace key. The host signs Willow entries with it, only in the configured communal namespace and under the configured path prefix.",
      },
    ],
    reason:
      'Serves the selected resources, as far as anyone may read them, as a Willow drop that other Willow peers can import.',
  },
  capabilities: [
    {
      name: 'storage',
      reason:
        'Read approved Atomic resources and propose reviewed unsigned export records.',
    },
  ],
  configSchema: {
    type: 'object',
    properties: {
      subjects: {
        type: 'array',
        items: { type: 'string' },
        description: 'Explicit Atomic resource subjects to export',
      },
      properties: {
        type: 'array',
        items: { type: 'string' },
        description:
          'Explicit property subjects included in each JSON-AD payload',
      },
      outputParent: {
        type: 'string',
        description:
          'Unsigned candidate job only: Atomic parent for reviewed unsigned export candidates',
      },
      namespace: {
        type: 'string',
        description:
          'Willow namespace id, 64 hex characters. The drop route needs a communal one (last byte even).',
      },
      subspace: {
        type: 'string',
        description:
          "Unsigned candidate job only: Willow subspace id, 64 hex characters. The drop route uses the installation's own key.",
      },
      pathPrefix: {
        type: 'array',
        items: { type: 'string' },
        description: 'Willow binary path components as hexadecimal strings',
      },
      timestamp: {
        type: 'string',
        description:
          'Unsigned candidate job only: explicit logical Willow U64 timestamp as decimal text; increase after source changes',
      },
    },
    required: ['subjects', 'properties', 'namespace', 'pathPrefix'],
  },
};

// Match the host's canonical atomic: scheme and legacy did:ad: alias without
// imposing a signature alphabet. The host owns deeper identifier validation.
function subjectId(value) {
  if (
    typeof value !== 'string' ||
    /\s/.test(value) ||
    [...value].some(
      char => char.charCodeAt(0) < 32 || char.charCodeAt(0) === 127,
    )
  )
    return false;
  if (/^https?:\/\/[^/?#]+/.test(value)) return true;
  const body = value.startsWith('atomic:')
    ? value.slice(7)
    : value.startsWith('did:ad:')
      ? value.slice(7)
      : '';

  return body.split(/[?#]/)[0].length > 0 && !body.startsWith('//');
}

function decimal(value) {
  if (
    typeof value !== 'string' ||
    !/^(0|[1-9][0-9]*)$/.test(value) ||
    value.length > 20
  )
    throw Error('Timestamp must be canonical U64 decimal text');

  return u64(BigInt(value));
}

/** Deterministic JSON serialization is an application payload choice, not Willow framing. */
export function canonicalJson(value, depth = 0) {
  if (depth > 32) throw Error('Payload nesting limit exceeded');
  if (value === null || typeof value === 'boolean' || typeof value === 'string')
    return JSON.stringify(value);
  if (typeof value === 'number' && Number.isFinite(value))
    return JSON.stringify(value);

  if (Array.isArray(value)) {
    if (value.length > 1024) throw Error('Payload array limit exceeded');

    return (
      '[' + value.map(item => canonicalJson(item, depth + 1)).join(',') + ']'
    );
  }

  if (
    value &&
    typeof value === 'object' &&
    (Object.getPrototypeOf(value) === Object.prototype ||
      Object.getPrototypeOf(value) === null)
  ) {
    const keys = Object.keys(value).sort();
    if (keys.length > 128) throw Error('Payload object limit exceeded');

    return (
      '{' +
      keys
        .map(
          key =>
            JSON.stringify(key) + ':' + canonicalJson(value[key], depth + 1),
        )
        .join(',') +
      '}'
    );
  }

  throw Error('Payload contains a non-JSON value');
}

function config(raw) {
  if (!raw || !subjectId(raw.outputParent))
    throw Error('Configure an Atomic output parent');

  for (const field of ['subjects', 'properties']) {
    if (
      !Array.isArray(raw[field]) ||
      !raw[field].length ||
      raw[field].length > MAX_SUBJECTS ||
      !raw[field].every(subjectId) ||
      new Set(raw[field]).size !== raw[field].length
    )
      throw Error('Configure bounded unique ' + field);
  }

  if (raw.subjects.includes(raw.outputParent))
    throw Error('Output parent cannot be a source');
  if (
    !/^[a-fA-F0-9]{64}$/.test(raw.namespace) ||
    !/^[a-fA-F0-9]{64}$/.test(raw.subspace)
  )
    throw Error('Willow identifiers must be 32-byte public keys');
  if (!Array.isArray(raw.pathPrefix))
    throw Error('Configure binary path prefix');
  const prefix = validatePath(raw.pathPrefix.map(unhex));

  return {
    ...raw,
    prefix,
    namespaceBytes: unhex(raw.namespace),
    subspaceBytes: unhex(raw.subspace),
    time: decimal(raw.timestamp),
  };
}

/** Reads only an explicitly configured Atomic subject and selected properties.
 * Returns an unsigned Entry and payload, not a Meadowcap AuthorisedEntry.
 */
export function exportCandidate(ctx, raw, subject) {
  const c = config(raw);
  if (!c.subjects.includes(subject))
    throw Error('Subject is not approved for export');
  const resource = ctx.read(subject),
    selected = Object.create(null);
  selected['@id'] = subject;

  for (const property of c.properties) {
    if (Object.prototype.hasOwnProperty.call(resource, property))
      selected[property] = resource[property];
  }

  const payload = utf8(canonicalJson(selected));
  if (payload.length > MAX_PAYLOAD_BYTES) throw Error('Payload exceeds 64 KiB');
  const entry = {
    namespace: c.namespaceBytes,
    subspace: c.subspaceBytes,
    path: validatePath([...c.prefix, utf8(subject)]),
    timestamp: c.time,
    payloadLength: BigInt(payload.length),
    payloadDigest: william3(payload),
  };

  return { entry, entryBytes: encodeEntry(entry), payload };
}
/** Structural and payload-integrity validation only. No signature/capability check. */
export function checkCandidate(entryBytes, payload) {
  const entry = decodeEntry(entryBytes, { canonical: true });
  if (
    !(payload instanceof Uint8Array) ||
    payload.length > MAX_PAYLOAD_BYTES ||
    BigInt(payload.length) !== entry.payloadLength
  )
    throw Error('Payload length mismatch or limit exceeded');
  if (hex(william3(payload)) !== hex(entry.payloadDigest))
    throw Error('WILLIAM3 payload digest mismatch');

  return entry;
}
/** Existing Atomic sandbox job: proposes persisted candidate resources for review.
 * No remote peer receives these proposals and no signing key is ever handled.
 */
export function run(ctx) {
  try {
    const c = config(ctx.config),
      intents = [];

    for (const subject of c.subjects) {
      const { entry, entryBytes, payload } = exportCandidate(ctx, c, subject);
      const key =
        'willow-candidate:' +
        hex(
          william3(
            utf8(
              canonicalJson({
                namespace: hex(entry.namespace),
                subspace: hex(entry.subspace),
                path: entry.path.map(hex),
              }),
            ),
          ),
        );
      const matches = ctx
        .query(P.localId, key)
        .filter(id => ctx.read(id)[P.parent] === c.outputParent);
      if (matches.length > 1)
        throw Error('Duplicate export candidate identity');
      const envelope = {
        format: 'atomic-willow-signing-candidate-v1',
        status: 'unsigned',
        source: subject,
        mediaType: 'application/ad+json',
        entryHex: hex(entryBytes),
        payloadHex: hex(payload),
      };
      const serialized = canonicalJson(envelope);
      const set = {
        [P.name]: 'Unsigned Willow export: ' + subject,
        [P.description]: serialized,
        [P.localId]: key,
        [P.baseline]: {
          ...envelope,
          values: {
            [P.name]: 'Unsigned Willow export: ' + subject,
            [P.description]: serialized,
          },
          previous: {},
        },
      };

      if (!matches.length)
        intents.push({
          op: 'create',
          localId: key,
          parent: c.outputParent,
          isA: [],
          set,
        });
      else {
        const existing = ctx.read(matches[0]),
          previous = existing[P.baseline];
        if (
          !previous ||
          previous.format !== envelope.format ||
          !previous.values ||
          existing[P.description] !== previous.values[P.description] ||
          existing[P.name] !== previous.values[P.name] ||
          previous.values[P.description] !==
            canonicalJson({
              format: previous.format,
              status: previous.status,
              source: previous.source,
              mediaType: previous.mediaType,
              entryHex: previous.entryHex,
              payloadHex: previous.payloadHex,
            })
        )
          throw Error('Local candidate edits require manual reconciliation');
        const oldEntry = checkCandidate(
          unhex(previous.entryHex),
          unhex(previous.payloadHex),
        );
        if (
          previous.source !== subject ||
          hex(oldEntry.namespace) !== hex(entry.namespace) ||
          hex(oldEntry.subspace) !== hex(entry.subspace) ||
          canonicalJson(oldEntry.path.map(hex)) !==
            canonicalJson(entry.path.map(hex))
        )
          throw Error('Existing candidate identity does not match source');
        if (
          previous.entryHex === envelope.entryHex &&
          previous.payloadHex === envelope.payloadHex
        )
          continue;
        if (entry.timestamp <= oldEntry.timestamp)
          throw Error(
            'Increase logical timestamp before replacing an export candidate',
          );
        set[P.baseline].previous = previous.values;
        intents.push({ op: 'set', subject: matches[0], set });
      }
    }

    return { intents, problems: [] };
  } catch (error) {
    return {
      intents: [],
      problems: [{ severity: 'error', message: error.message }],
    };
  }
}

function routeConfig(raw) {
  if (!raw) throw Error('The plugin is not configured');

  for (const field of ['subjects', 'properties']) {
    if (
      !Array.isArray(raw[field]) ||
      !raw[field].length ||
      raw[field].length > MAX_SUBJECTS ||
      !raw[field].every(subjectId) ||
      new Set(raw[field]).size !== raw[field].length
    )
      throw Error('Configure bounded unique ' + field);
  }

  if (!/^[a-fA-F0-9]{64}$/.test(raw.namespace))
    throw Error('The Willow namespace must be 64 hex characters');
  if (!Array.isArray(raw.pathPrefix))
    throw Error('Configure binary path prefix');

  return { ...raw, prefix: validatePath(raw.pathPrefix.map(unhex)) };
}

/** The JSON-AD payload of the selected properties, as exportCandidate makes it. */
function payloadOf(subject, resource, properties) {
  const selected = Object.create(null);
  selected['@id'] = subject;

  for (const property of properties) {
    if (Object.prototype.hasOwnProperty.call(resource, property))
      selected[property] = resource[property];
  }

  const payload = utf8(canonicalJson(selected));
  if (payload.length > MAX_PAYLOAD_BYTES) throw Error('Payload exceeds 64 KiB');

  return payload;
}

/**
 * One source as a host-authorised Willow entry. The timestamp is the
 * source's last commit time, read as the data model recommends, so an
 * unchanged source yields the same entry (and the host the same signature),
 * and an edit a newer one. The host tells that time (`ctx.willow.source`:
 * commits are not always readable resources) and refuses to sign unless the
 * source is still at that commit and readable by this route's principal.
 */
export function authorisedEntry(ctx, c, subspace, subject) {
  const revision = ctx.willow.source(WILLOW_KEY, subject);
  const resource = ctx.read(subject);
  const commit = resource[P.lastCommit];
  if (typeof commit !== 'string' || !commit)
    throw Error('A selected resource has no last commit');
  if (commit !== revision.commit)
    throw Error('A selected resource changed while it was read; try again');
  const timestamp = decimal(revision.timestamp);
  // The host's reading of the commit time must be the data model's.
  if (
    !Number.isSafeInteger(revision.committedAt) ||
    willowTime(BigInt(revision.committedAt)) !== timestamp
  )
    throw Error('The host reads the commit time differently');
  const payload = payloadOf(subject, resource, c.properties);
  const entry = {
    namespace: unhex(c.namespace),
    subspace,
    path: validatePath([...c.prefix, utf8(subject)]),
    timestamp,
    payloadLength: BigInt(payload.length),
    payloadDigest: william3(payload),
  };
  const entryHex = hex(encodeEntry(entry));
  const signed = ctx.willow.authorise({
    key: WILLOW_KEY,
    entry: entryHex,
    source: { subject, commit },
  });
  if (signed.entry !== entryHex)
    throw Error('The host signed other bytes than the ones asked for');

  return { entry, signature: unhex(signed.signature), payload };
}

/**
 * `GET /willow.drop`: every selected resource the public may read, as one
 * Willow drop (raw bytes). Anonymous, so it exports nothing a visitor could
 * not read anyway. All or nothing: a resource that cannot be read or signed
 * fails the request, and the reason goes to the run log, not the response.
 */
export function handle(ctx) {
  try {
    const c = routeConfig(ctx.config);
    const { subspace } = ctx.willow.subspace(WILLOW_KEY);
    const items = c.subjects.map(subject =>
      authorisedEntry(ctx, c, unhex(subspace), subject),
    );

    return {
      response: {
        status: 200,
        headers: {
          'content-type': 'application/octet-stream',
          'cache-control': 'no-cache',
        },
        bodyBase64: base64(encodeDrop(items)),
      },
      problems: [],
    };
  } catch (error) {
    return {
      response: {
        status: 503,
        headers: { 'content-type': 'text/plain; charset=utf-8' },
        body: 'This Willow drop cannot be built right now; the installation run log says why.',
      },
      problems: [{ severity: 'error', message: error.message }],
    };
  }
}
