// Bundles plugin.mjs, sha256.mjs and manifest.json into plugin.js, the single
// module the host runs. Deterministic: the same inputs give the same bytes.
//
//   node integrations/fediverse/build.mjs
import { readFile, writeFile } from 'node:fs/promises';

const source = await readFile(new URL('./plugin.mjs', import.meta.url), 'utf8');
const hash = await readFile(new URL('./sha256.mjs', import.meta.url), 'utf8');
const manifest = JSON.parse(
  await readFile(new URL('./manifest.json', import.meta.url), 'utf8'),
);
const importLine = "import { sha256 } from './sha256.mjs';\n";
if (!source.includes(importLine))
  throw new Error('plugin.mjs must import sha256 exactly once, as build.mjs expects');
await writeFile(
  new URL('./plugin.js', import.meta.url),
  '// Generated by build.mjs; edit plugin.mjs or manifest.json.\n' +
    `export const manifest = ${JSON.stringify(manifest)};\n` +
    hash +
    '\n' +
    source.replace(importLine, ''),
);
