overlay: 1.0.0
extends: https://raw.githubusercontent.com/ontola/openapi-directory/5731d0e2be09f5ad46aca269c0360d192fe5b54d/APIs/googleapis.com/cloudbuild/v1beta1/openapi.yaml
info:
  title: Pagination Schemes
  version: 1.0.0
actions:
  - target: $.components
    update:
      paginationSchemes:
        pageToken:
          type: pageToken
          request:
            queryParameters:
              pageToken:
                role: pageToken
              pageSize:
                role: pageSize
          response:
            bodyFields:
              nextPageToken:
                role: nextPageToken
