import { readFileSync, writeFileSync } from 'node:fs';
import { manifest } from './plugin.mjs';
const source = readFileSync(new URL('./plugin.mjs', import.meta.url), 'utf8');
const outputs = {
  'plugin.js': '// Generated by build.mjs; edit plugin.mjs.\n' + source,
  'plugin.json':
    JSON.stringify(manifest, null, 2).replace(
      /\[\n\s*((?:"[^"]*"(?:,\n\s*)?)+)\n\s*\]/g,
      (_, values) => '[' + values.replace(/,\n\s*/g, ', ') + ']',
    ) + '\n',
};

for (const [name, content] of Object.entries(outputs)) {
  const target = new URL(name, import.meta.url);
  if (process.argv.includes('--check')) {
    if (readFileSync(target, 'utf8') !== content)
      throw new Error(name + ' is stale');
  } else writeFileSync(target, content);
}
