overlay: 1.0.0
extends: https://raw.githubusercontent.com/ontola/openapi-directory/a52315437677ca06a8a152cb52aeb287f23f5323/APIs/googleapis.com/cloudbuild/v1alpha1/openapi.yaml
info:
  title: Pagination Schemes
  version: 1.0.0
actions:
  - target: $.components
    update:
      paginationSchemes:
        pageToken:
          type: pageToken
          request:
            queryParameters:
              pageToken:
                role: pageToken
              pageSize:
                role: pageSize
          response:
            bodyFields:
              nextPageToken:
                role: nextPageToken
