// @wc-ignore-file
import {
  fetchAccountContext,
  fetchNamed,
  type RawNamed,
} from './clockifyApi.js';
import {
  absenceCandidates,
  MARGIN_MS,
  rawFromCanonical,
  readOne,
  readRange,
  timeEntries,
  totalMs,
  unknownIntervals,
  type ReadContext,
} from './clockifyObserve.js';
import type { Settings } from './config.js';
import { leaseHeldElsewhere } from './lease.js';
import { ObservationLog } from './observationLog.js';
import type { Mirror } from './observations.js';
import { TIME_ENTRY as TIME_ENTRY_CLASS } from './fields.js';
import { atomic } from './ontology.js';
import { projectEntries, type ProjectedEntry } from './project.js';
import type { CompleteSchema } from './schema.js';
import type { PluginStore } from './store.js';
import type { ProxyTransport } from './transport.js';
import {
  createKey,
  entryBoundaries,
  mirrorEntry,
  newRowValues,
  planChange,
  setPerson,
  planCreate,
  retireRow,
  settleCreates,
  sortChanges,
  syncRow,
  type EntryValues,
  type PendingChange,
  type ProviderWon,
} from './writeBack.js';
import type { WriteContext } from '../devonian/clockify/lens/index.js';

const DAY = 86_400_000;

export interface SyncResult {
  created: number;
  updated: number;
  unchanged: number;
  /** Rows of entries Clockify confirmed deleted (GET by id: 404). */
  removed: number;
  /**
   * On a table the app is a view of, which it may not delete rows of: rows
   * of entries Clockify confirmed deleted, kept as rows of their own (the
   * app's extras taken off) for the person to delete (`retireRow`).
   */
  kept: number;
  /** Rows that differ from what they last agreed on with Clockify: the
   * "Changes to send" list (#123 M3). Nothing is sent without review. */
  review: PendingChange[];
  /** Fields changed both here and in Clockify: Clockify's value was kept. */
  providerWon: ProviderWon[];
  /** Sends a closed frame left unconfirmed, settled by this pass's read. */
  recovered: Recovered[];
  /** Non-fatal: e.g. project names unavailable, so rows keep raw ids only. */
  warnings: string[];
  log: LogReport;
  /** Another open copy of the app holds the send lease (#123 M5): until
   * when, ISO 8601. Its unconfirmed creates were left alone. */
  sendingElsewhereUntil?: string;
  /** The profile time zone used for the window, and the workspace's
   * forceProjects, as read this pass (absent when unknown). */
  account: {
    timeZone?: string;
    forceProjects?: boolean;
    weekStart?: string;
    userName?: string;
    workspaceName?: string;
  };
  /** The mirror after this pass, and the names read for it: what the
   * timesheet views show (#89). */
  mirror: Mirror;
  projects: RawNamed[];
  members: RawNamed[];
}

export interface Recovered {
  entryId: string;
  title: string;
  /** Clockify had the values the row sent. False: it did not; the change
   * is listed again. */
  applied: boolean;
}

/** Saving rows: `done` of `total` projected entries (#89 frame H). */
export interface SyncProgress {
  phase: 'save';
  done: number;
  total: number;
}

export interface LogReport {
  /** Incrementals stored by this sync; 0 when nothing changed. */
  incrementals: number;
  snapshotWritten: boolean;
  /** Entries missing from a complete list read, re-checked next sync. */
  candidates: number;
  /** Milliseconds of the look-back window no complete read covers. */
  unknownMs: number;
}

export interface SyncOptions {
  /** Wall clock for observation timestamps. Defaults to `Date.now`. */
  clock?: () => number;
  /** Observation ids. Defaults to a time-ordered random id. */
  newId?: () => string;
  /** Names this app instance in the log. Defaults to a random id. */
  device?: string;
  onProgress?: (progress: SyncProgress) => void;
}

const randomHex = (bytes: number) =>
  Array.from(crypto.getRandomValues(new Uint8Array(bytes)), b =>
    b.toString(16).padStart(2, '0'),
  ).join('');

export const newObservationId = (clock: () => number = Date.now) =>
  `${clock().toString(36).padStart(9, '0')}-${randomHex(8)}`;

/** Generated per page load: the frame has no storage to keep one in. */
export const SESSION_DEVICE = `frame-${randomHex(6)}`;

/** The table note before 0.2.0; replaced on the next sync. */
export const READ_ONLY_TABLE_NOTE =
  'Generated by the Clockify timesheets app from what it last read in Clockify. Read-only: edits made here are overwritten on the next sync.';

/** The table note of 0.2.0 to 0.4.0; replaced on the next sync. */
export const ROW_TABLE_NOTE =
  'Filled by the Clockify timesheets app from what it last read in Clockify. Edits to Name, Start, End, Billable and Project are listed under "Changes to send" in the app the next time it opens, and reach Clockify only once sent there. If the same field was also changed in Clockify, Clockify\'s value is kept.';

export const GENERATED_TABLE_NOTE =
  'Filled by the Clockify timesheets app from what it last read in Clockify, as shared Time entry rows. Project and Person link to rows of the app\'s Projects and People tables. Edits to Name, Start, End, Billable and Project are listed under "Changes to send" in the app the next time it opens, and reach Clockify only once sent there. If the same field was also changed in Clockify, Clockify\'s value is kept.';

/**
 * One sync pass: the observation log (#123 M1) and the rows (M3):
 *
 * 1. Confirm the absence candidates of earlier passes with a GET by id each:
 *    404 confirms the deletion, 200 restores the entry (it was skipped or
 *    moved, not deleted). A failing GET leaves the candidate for next time.
 * 2. Read the look-back window, starting 24 h earlier (the margin), as one
 *    observation; append it as a mask-diff against the mirror. The bounds
 *    are sent as wall-clock time in the user's profile time zone, read
 *    from `GET /user` each pass along with the workspace's
 *    `forceProjects`, and recorded as the UTC span they cover.
 * 3. Compact when the tail is long enough, and save the log head.
 * 4. Bring the table's rows up to date with the mirror: completed
 *    `REGULAR` entries (the lens skips running timers and breaks) are
 *    created or updated by `clockify-entry-id`, and a row whose entry
 *    Clockify confirmed deleted is destroyed (on a table the app is a view
 *    of, which it may not delete rows of: kept, with the app's extras taken
 *    off, `retireRow`). A row edited here keeps its
 *    edit (#177 Q5, reversing #97 answer 2): each row is compared with its
 *    baseline and with Clockify (`writeBack.ts` `syncRow`), and what it
 *    changed comes back as `review`, to be sent only from the app's
 *    "Changes to send". A field changed on both sides takes Clockify's
 *    value (`providerWon`).
 *
 * A failure of the window's first page fails the pass; only step 1's
 * re-checks, if any, are saved. A failure on a later page keeps what was
 * read (incomplete: no absences, no coverage), saves it, and fails the pass.
 * Either way the rows are not touched. Nothing is written to Clockify
 * here; `writeBack.ts` `sendChanges` does that, after review.
 *
 * Row identity is a stored `clockify-entry-id` found with `store.query()`,
 * restricted to children of the app's table (`query` is drive-scoped).
 * Requests are sequential; each is one `store.proxy.request` round trip.
 */
export async function syncClockify(
  store: PluginStore,
  transport: ProxyTransport,
  settings: Settings,
  schema: CompleteSchema,
  now = Date.now(),
  options: SyncOptions = {},
): Promise<SyncResult> {
  const clock = options.clock ?? Date.now;
  const account = await fetchAccountContext(transport, settings.workspaceId);
  const context: ReadContext = {
    transport,
    workspaceId: settings.workspaceId,
    userId: settings.userId,
    ...(account.timeZone ? { timeZone: account.timeZone } : {}),
    clock,
    newId: options.newId ?? (() => newObservationId(clock)),
    device: options.device ?? SESSION_DEVICE,
  };
  const log = await ObservationLog.open(store, schema, { clock });
  const warnings: string[] = [...account.warnings];

  for (const candidate of absenceCandidates(log.mirror)) {
    try {
      await log.append(await readOne(context, candidate.id));
    } catch (error) {
      warnings.push(
        `Could not re-check entry ${candidate.id}: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }

  const window = { from: now - settings.lookbackDays * DAY, to: now };
  let read: Awaited<ReturnType<typeof readRange>>;

  try {
    read = await readRange(context, window.from - MARGIN_MS, window.to);
  } catch (error) {
    await log.flush();
    throw error;
  }

  await log.append(read.observation);

  if (read.error) {
    await log.flush();
    throw read.error;
  }

  const projects = await fetchNamed(
    transport,
    settings.workspaceId,
    'projects',
  );
  const members = await fetchNamed(transport, settings.workspaceId, 'users');
  warnings.push(
    ...[projects.warning, members.warning].filter((w): w is string => !!w),
  );
  const snapshotWritten = await log.compactIfNeeded();
  await log.flush();
  const holder = await leaseHeldElsewhere(store, schema, {
    device: context.device,
    clock,
  });

  const rows = await projectRows(
    store,
    schema,
    log,
    projects.items,
    members.items,
    {
      now,
      ...(account.forceProjects !== undefined
        ? { forceProjects: account.forceProjects }
        : {}),
      projects: projects.items,
    },
    options.onProgress,
    settings.userId,
    !!holder,
  );

  return {
    ...rows,
    warnings,
    ...(holder ? { sendingElsewhereUntil: holder.until } : {}),
    log: {
      incrementals: log.appended,
      snapshotWritten,
      candidates: absenceCandidates(log.mirror).length,
      unknownMs: totalMs(unknownIntervals(log.mirror, settings, window, now)),
    },
    account: {
      ...(account.timeZone ? { timeZone: account.timeZone } : {}),
      ...(account.forceProjects !== undefined
        ? { forceProjects: account.forceProjects }
        : {}),
      ...(account.weekStart ? { weekStart: account.weekStart } : {}),
      ...(account.userName ? { userName: account.userName } : {}),
      ...(account.workspaceName
        ? { workspaceName: account.workspaceName }
        : {}),
    },
    mirror: log.mirror,
    projects: projects.items,
    members: members.items,
  };
}

async function projectRows(
  store: PluginStore,
  schema: CompleteSchema,
  log: ObservationLog,
  projects: RawNamed[],
  members: RawNamed[],
  write: WriteContext,
  onProgress?: SyncOptions['onProgress'],
  userId = '',
  busy = false,
) {
  const result = {
    created: 0,
    updated: 0,
    unchanged: 0,
    removed: 0,
    kept: 0,
    review: [] as PendingChange[],
    providerWon: [] as ProviderWon[],
    recovered: [] as Recovered[],
  };
  // New rows whose create got no answer: bound to what Clockify made, or
  // listed again (#123 S15). Before the loop, so no entry gets two rows.
  const { settled, pending } = await settleCreates(store, schema, log.mirror, {
    userId,
    now: write.now,
    projects: write.projects,
    members,
    busy,
  });
  const boundNow = new Map(
    settled.filter(s => s.entryId).map(s => [s.entryId!, s.subject]),
  );

  for (const s of settled)
    result.recovered.push({
      entryId: s.entryId ?? createKey(s.subject),
      title: s.title,
      applied: !!s.entryId,
    });

  const own = new Set(
    await store.query({ property: atomic.parent, value: schema.table }),
  );
  const rowOf = async (entryId: string) =>
    boundNow.get(entryId) ??
    (await store.query({ property: schema.row.entryId, value: entryId })).find(
      s => own.has(s),
    );
  const boundaries = entryBoundaries(log.mirror);

  // Only the app's own table: a row grant never writes the table itself.
  if (schema.own) {
    const table = await store.getResource(schema.table);
    const note = table.get(atomic.description);

    if (!note || note === READ_ONLY_TABLE_NOTE || note === ROW_TABLE_NOTE) {
      table.set(atomic.description, GENERATED_TABLE_NOTE);
      await table.save();
    }
  }

  // The Projects table follows Clockify's project list (#177 Q11): a row
  // per active project, named as Clockify names it.
  for (const project of projects)
    if (project.archived !== true)
      await schema.links.ensure('project', project.id, project.name, {
        rename: true,
      });

  const entries = timeEntries(log.mirror);
  const projected = projectEntries(
    entries.filter(r => !r.deletedAt).map(rawFromCanonical),
    projects,
    members,
  ).sort((a, b) => a.start - b.start || (a.entryId < b.entryId ? -1 : 1));

  for (const [done, entry] of projected.entries()) {
    onProgress?.({ phase: 'save', done, total: projected.length });
    const remote = remoteValues(entry);

    // The row links to the project row; its name is the project's here.
    if (remote.projectId) {
      await schema.links.ensure('project', remote.projectId, remote.project, {
        rename: !!remote.project,
      });
      remote.project =
        schema.links.nameOf('project', remote.projectId) ?? remote.project;
    }

    const subject = await rowOf(entry.entryId);

    if (!subject) {
      const created = await store.newResource({
        parent: schema.table,
        isA: [TIME_ENTRY_CLASS],
        propVals: {
          ...(await newRowValues(schema, remote)),
          [schema.row.entryId]: entry.entryId,
        },
      });
      if (
        await setPerson(
          created,
          schema,
          entry.memberId,
          entry.memberName ?? null,
        )
      )
        await created.save();
      own.add(created.subject);
      result.created++;
      continue;
    }

    const row = await store.getResource(subject);
    const personChanged = await setPerson(
      row,
      schema,
      entry.memberId,
      entry.memberName ?? null,
    );
    if (personChanged) await row.save();
    const synced = await syncRow(row, schema, remote);

    if (synced.valuesChanged || personChanged) result.updated++;
    else result.unchanged++;
    if (synced.notice) result.providerWon.push(synced.notice);
    if (synced.recovered)
      result.recovered.push({
        entryId: entry.entryId,
        title: remote.name,
        applied: synced.recovered === 'applied',
      });
    const change = planChange(
      synced.state,
      mirrorEntry(log.mirror, entry.entryId),
      write,
      boundaries,
    );
    if (change) result.review.push(change);
  }

  // New rows from range edits, not yet created in Clockify.
  for (const created of pending) result.review.push(planCreate(created, write));

  for (const gone of entries.filter(r => r.deletedAt)) {
    const subject = await rowOf(gone.id);
    if (!subject) continue;
    if (await retireRow(await store.getResource(subject), schema))
      result.removed++;
    else result.kept++;
    own.delete(subject);
  }

  result.review = sortChanges(result.review);

  return result;
}

/** A row's synced values, from the lens's projection of a Clockify entry. */
export function remoteValues(entry: ProjectedEntry): EntryValues {
  return {
    name: entry.name,
    start: entry.start,
    end: entry.end,
    billable: entry.billable === true,
    projectId: entry.projectId ?? null,
    project: entry.projectName ?? null,
  };
}
